import { useSyncExternalStore } from "react";

/**
 * Whether the viewport is narrow enough that the sidebar becomes a drawer.
 *
 * Generated by shadcn alongside `ui/sidebar.tsx` and rewritten here. The
 * shipped version subscribes in an effect and calls `setState` from its body,
 * which `react-hooks/set-state-in-effect` rejects and which costs a cascading
 * render on every mount. `useSyncExternalStore` is the primitive React
 * provides for exactly this — subscribing to something outside React that has
 * a readable current value — so the reader never renders a wrong answer first.
 *
 * The breakpoint matches `ui/sidebar.tsx`'s own `md:` boundary; changing one
 * without the other splits the desktop rail from the mobile drawer.
 */
const MOBILE_BREAKPOINT = 768;
const QUERY = `(max-width: ${MOBILE_BREAKPOINT - 1}px)`;

function subscribe(onStoreChange: () => void): () => void {
  const query = window.matchMedia(QUERY);
  query.addEventListener("change", onStoreChange);
  return () => query.removeEventListener("change", onStoreChange);
}

function getSnapshot(): boolean {
  return window.matchMedia(QUERY).matches;
}

/** No SSR here, but the hook still owes the signature a server snapshot. */
function getServerSnapshot(): boolean {
  return false;
}

export function useIsMobile(): boolean {
  return useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
}
