import { describe, expect, it } from "vitest";

import { findOpenApiProblem } from "../schema-payload.ts";

const url = "https://bull-ledger.voynan.com/system/schema/";

/** What the SPA's asset network answers with when `/system/*` is not proxied. */
const appShell = `<!doctype html>
<html lang="en">
  <head>
    <title>BullLedger</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`;

describe("findOpenApiProblem", () => {
  it("accepts a YAML document", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: "application/vnd.oai.openapi",
        body: "openapi: 3.0.3\ninfo:\n  title: BullLedger API\n",
      }),
    ).toBeNull();
  });

  it("accepts a JSON document", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: "application/vnd.oai.openapi+json",
        body: '{"openapi": "3.0.3", "info": {"title": "BullLedger API"}}',
      }),
    ).toBeNull();
  });

  it("accepts a document behind comments and a directives-end marker", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: null,
        body: "# Generated by drf-spectacular\n\n---\nopenapi: 3.0.3\n",
      }),
    ).toBeNull();
  });

  it("accepts a document behind a byte order mark", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: null,
        body: "\uFEFFopenapi: 3.0.3\n",
      }),
    ).toBeNull();
  });

  it("accepts a Swagger 2 document, so the error names the real problem", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: null,
        body: 'swagger: "2.0"\ninfo:\n  title: BullLedger API\n',
      }),
    ).toBeNull();
  });

  it("rejects the app shell served in the schema's place", () => {
    const problem = findOpenApiProblem({
      url,
      contentType: "text/html; charset=utf-8",
      body: appShell,
    });

    expect(problem).toContain(url);
    expect(problem).toContain("text/html");
    expect(problem).toContain("<!doctype html>");
  });

  it("rejects a plain-text body that merely arrived with a 200", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: "text/plain",
        body: "API_ORIGIN is not set. Set it in wrangler.jsonc and redeploy.",
      }),
    ).toContain("API_ORIGIN is not set");
  });

  it("rejects an empty body", () => {
    expect(
      findOpenApiProblem({ url, contentType: "text/plain", body: "  \n" }),
    ).toContain("empty");
  });

  it("rejects JSON that is not a schema", () => {
    expect(
      findOpenApiProblem({
        url,
        contentType: "application/json",
        body: '{"detail": "Not found."}',
      }),
    ).toContain('{"detail": "Not found."}');
  });

  it("rejects a body of nothing but comments", () => {
    expect(
      findOpenApiProblem({ url, contentType: null, body: "# nothing here\n" }),
    ).not.toBeNull();
  });

  it("says the content type is missing rather than printing null", () => {
    const problem = findOpenApiProblem({
      url,
      contentType: null,
      body: appShell,
    });

    expect(problem).toContain("no content type");
    expect(problem).not.toContain("null");
  });

  it("truncates a long first line instead of dumping the payload", () => {
    const problem = findOpenApiProblem({
      url,
      contentType: "text/html",
      body: "x".repeat(5_000),
    });

    expect(problem).toContain("…");
    expect(problem!.length).toBeLessThan(500);
  });
});
